version: '2'

services:

  mysql:
    image: mysql:8.0.16
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/docker-data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: springbucks
      MYSQL_USER: springbucks
      MYSQL_PASSWORD: springbucks
      MYSQL_ROOT_PASSWORD: root_password

  waiter-service:
    build: ../
    image: helanzhu/waiter-service:1.0.0
    container_name: waiter-service
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - mysql