version: '3'

services:
  mysql:
    image: mysql:8.0.16
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=springbucks
      - MYSQL_USER=springbucks 
      - MYSQL_PASSWORD=springbucks 
      - MYSQL_ROOT_PASSWORD=root_password

  consul:
    image: consul:latest
    expose:
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
      - 8600
    ports:
      - 8500:8500

  zookeeper:
    image: zookeeper:latest
    expose:
      - 2181
      - 2888
      - 3888

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    expose:
      - 9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  zipkin:
    image: openzipkin/zipkin:latest
    expose:
      - 9411
    ports:
      - 9411:9411

  waiter-service:
    image: helanzhu/waiter-service:0.0.1-SNAPSHOT
    depends_on:
      - mysql
      - consul
      - kafka
      - zipkin
    expose:
      - 8080
    ports:
      - 8080:8080

  barista-service:
    image: helanzhu/barista-service:0.0.1-SNAPSHOT
    depends_on:
      - mysql
      - consul
      - kafka
      - zipkin

  customer-service:
    image: helanzhu/customer-service:0.0.1-SNAPSHOT
    depends_on:
      - waiter-service
      - consul
      - kafka
      - zipkin
    expose:
      - 8090
    ports:
      - 8090:8090