spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
      bindings:
        finishedOrders:
          group: waiter-service
  datasource:
    initialization-mode: always
    #    url: jdbc:mysql://mysql:3306/springbucks?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://localhost:3306/springbucks?allowPublicKeyRetrieval=true&useSSL=false
    username: springbucks
    password: springbucks
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: waiter-service
    author: "Kevin Jin"

order:
  discount: 95

resilience4j:
  ratelimiter:
    limiters:
      coffee:
        limit-for-period: 5
        limit-refresh-period-in-millis: 30000
        timeout-in-millis: 5000
        subscribe-for-events: true
        register-health-indicator: true
      order:
        limit-for-period: 3
        limit-refresh-period-in-millis: 30000
        timeout-in-millis: 3000
        subscribe-for-events: true
        register-health-indicator: true


server:
  port: 8080
#  compression:
#    enabled: true
#    min-response-size: 512B
#  error:
#    include-stacktrace: always
#    include-exception: true
